// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_Managment_system.Data;

#nullable disable

namespace University_Managment_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University_Managment_system.Entity.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Full Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex("DeptId")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DeptId = 1,
                            Email = "ahmed.mohamed@university.edu.eg",
                            FullName = "Ahmed Mohamed",
                            Password = "admin123"
                        },
                        new
                        {
                            Id = 102,
                            DeptId = 2,
                            Email = "mona.ali@university.edu.eg",
                            FullName = "Mona Ali",
                            Password = "admin456"
                        },
                        new
                        {
                            Id = 103,
                            DeptId = 3,
                            Email = "youssef.hassan@university.edu.eg",
                            FullName = "Youssef Hassan",
                            Password = "admin789"
                        },
                        new
                        {
                            Id = 104,
                            DeptId = 4,
                            Email = "fatma.mahmoud@university.edu.eg",
                            FullName = "Fatma Mahmoud",
                            Password = "admin101"
                        });
                });

            modelBuilder.Entity("University_Managment_system.Entity.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Credits")
                        .HasColumnType("float")
                        .HasColumnName("Credits");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 301,
                            Credits = 3.0,
                            DeptId = 1,
                            DoctorId = 201,
                            Name = "Programming Fundamentals"
                        },
                        new
                        {
                            Id = 302,
                            Credits = 4.0,
                            DeptId = 1,
                            DoctorId = 205,
                            Name = "Data Structures"
                        },
                        new
                        {
                            Id = 303,
                            Credits = 3.0,
                            DeptId = 2,
                            DoctorId = 202,
                            Name = "Database Systems"
                        },
                        new
                        {
                            Id = 304,
                            Credits = 3.0,
                            DeptId = 2,
                            DoctorId = 206,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 305,
                            Credits = 4.0,
                            DeptId = 4,
                            DoctorId = 204,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 306,
                            Credits = 4.0,
                            DeptId = 4,
                            DoctorId = 208,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 307,
                            Credits = 3.0,
                            DeptId = 1,
                            DoctorId = 209,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 308,
                            Credits = 3.0,
                            DeptId = 1,
                            DoctorId = 213,
                            Name = "Operating Systems"
                        },
                        new
                        {
                            Id = 309,
                            Credits = 3.0,
                            DeptId = 2,
                            DoctorId = 210,
                            Name = "Network Security"
                        },
                        new
                        {
                            Id = 310,
                            Credits = 4.0,
                            DeptId = 2,
                            DoctorId = 214,
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 311,
                            Credits = 4.0,
                            DeptId = 4,
                            DoctorId = 212,
                            Name = "Data Mining"
                        },
                        new
                        {
                            Id = 312,
                            Credits = 4.0,
                            DeptId = 4,
                            DoctorId = 216,
                            Name = "Natural Language Processing"
                        },
                        new
                        {
                            Id = 313,
                            Credits = 3.0,
                            DeptId = 1,
                            DoctorId = 217,
                            Name = "Mobile Application Development"
                        },
                        new
                        {
                            Id = 314,
                            Credits = 3.0,
                            DeptId = 1,
                            DoctorId = 201,
                            Name = "Computer Graphics"
                        },
                        new
                        {
                            Id = 315,
                            Credits = 3.0,
                            DeptId = 2,
                            DoctorId = 202,
                            Name = "Information Security"
                        },
                        new
                        {
                            Id = 316,
                            Credits = 4.0,
                            DeptId = 2,
                            DoctorId = 206,
                            Name = "Big Data Analytics"
                        },
                        new
                        {
                            Id = 317,
                            Credits = 4.0,
                            DeptId = 4,
                            DoctorId = 204,
                            Name = "Deep Learning"
                        },
                        new
                        {
                            Id = 318,
                            Credits = 4.0,
                            DeptId = 4,
                            DoctorId = 208,
                            Name = "Computer Vision"
                        },
                        new
                        {
                            Id = 319,
                            Credits = 3.0,
                            DeptId = 1,
                            DoctorId = 209,
                            Name = "Human-Computer Interaction"
                        },
                        new
                        {
                            Id = 320,
                            Credits = 3.0,
                            DeptId = 1,
                            DoctorId = 213,
                            Name = "Distributed Systems"
                        });
                });

            modelBuilder.Entity("University_Managment_system.Entity.Department", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptCode = "CS",
                            Description = "Department of Computer Science",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            DeptCode = "IT",
                            Description = "Department of Information Technology",
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 3,
                            DeptCode = "IS",
                            Description = "Department of Information Systems",
                            Name = "Information Systems"
                        },
                        new
                        {
                            Id = 4,
                            DeptCode = "AI",
                            Description = "Department of Artificial Intelligence",
                            Name = "Artificial Intelligence"
                        });
                });

            modelBuilder.Entity("University_Managment_system.Entity.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Full Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 201,
                            DeptId = 1,
                            Email = "ahmed.elsayed@university.edu.eg",
                            FullName = "Dr. Ahmed El-Sayed",
                            Password = "doctor123"
                        },
                        new
                        {
                            Id = 202,
                            DeptId = 2,
                            Email = "mona.hassan@university.edu.eg",
                            FullName = "Dr. Mona Hassan",
                            Password = "doctor456"
                        },
                        new
                        {
                            Id = 203,
                            DeptId = 3,
                            Email = "youssef.ali@university.edu.eg",
                            FullName = "Dr. Youssef Ali",
                            Password = "doctor789"
                        },
                        new
                        {
                            Id = 204,
                            DeptId = 4,
                            Email = "fatma.mahmoud@university.edu.eg",
                            FullName = "Dr. Fatma Mahmoud",
                            Password = "doctor101"
                        },
                        new
                        {
                            Id = 205,
                            DeptId = 1,
                            Email = "omar.ibrahim@university.edu.eg",
                            FullName = "Dr. Omar Ibrahim",
                            Password = "doctor202"
                        },
                        new
                        {
                            Id = 206,
                            DeptId = 2,
                            Email = "nada.samir@university.edu.eg",
                            FullName = "Dr. Nada Samir",
                            Password = "doctor303"
                        },
                        new
                        {
                            Id = 207,
                            DeptId = 3,
                            Email = "karim.adel@university.edu.eg",
                            FullName = "Dr. Karim Adel",
                            Password = "doctor404"
                        },
                        new
                        {
                            Id = 208,
                            DeptId = 4,
                            Email = "hana.tarek@university.edu.eg",
                            FullName = "Dr. Hana Tarek",
                            Password = "doctor505"
                        },
                        new
                        {
                            Id = 209,
                            DeptId = 1,
                            Email = "ali.khaled@university.edu.eg",
                            FullName = "Dr. Ali Khaled",
                            Password = "doctor606"
                        },
                        new
                        {
                            Id = 210,
                            DeptId = 2,
                            Email = "rana.sherif@university.edu.eg",
                            FullName = "Dr. Rana Sherif",
                            Password = "doctor707"
                        },
                        new
                        {
                            Id = 211,
                            DeptId = 3,
                            Email = "tamer.nabil@university.edu.eg",
                            FullName = "Dr. Tamer Nabil",
                            Password = "doctor808"
                        },
                        new
                        {
                            Id = 212,
                            DeptId = 4,
                            Email = "dina.hossam@university.edu.eg",
                            FullName = "Dr. Dina Hossam",
                            Password = "doctor909"
                        },
                        new
                        {
                            Id = 213,
                            DeptId = 1,
                            Email = "sherif.omar@university.edu.eg",
                            FullName = "Dr. Sherif Omar",
                            Password = "doctor1010"
                        },
                        new
                        {
                            Id = 214,
                            DeptId = 2,
                            Email = "laila.ahmed@university.edu.eg",
                            FullName = "Dr. Laila Ahmed",
                            Password = "doctor1111"
                        },
                        new
                        {
                            Id = 215,
                            DeptId = 3,
                            Email = "hassan.mohamed@university.edu.eg",
                            FullName = "Dr. Hassan Mohamed",
                            Password = "doctor1212"
                        },
                        new
                        {
                            Id = 216,
                            DeptId = 4,
                            Email = "nour.ali@university.edu.eg",
                            FullName = "Dr. Nour Ali",
                            Password = "doctor1313"
                        },
                        new
                        {
                            Id = 217,
                            DeptId = 1,
                            Email = "amr.tarek@university.edu.eg",
                            FullName = "Dr. Amr Tarek",
                            Password = "doctor1414"
                        },
                        new
                        {
                            Id = 218,
                            DeptId = 2,
                            Email = "sara.khaled@university.edu.eg",
                            FullName = "Dr. Sara Khaled",
                            Password = "doctor1515"
                        },
                        new
                        {
                            Id = 219,
                            DeptId = 3,
                            Email = "kareem.samir@university.edu.eg",
                            FullName = "Dr. Kareem Samir",
                            Password = "doctor1616"
                        },
                        new
                        {
                            Id = 220,
                            DeptId = 4,
                            Email = "dalia.adel@university.edu.eg",
                            FullName = "Dr. Dalia Adel",
                            Password = "doctor1717"
                        });
                });

            modelBuilder.Entity("University_Managment_system.Entity.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 401,
                            CourseId = 301
                        },
                        new
                        {
                            StudentId = 402,
                            CourseId = 303
                        },
                        new
                        {
                            StudentId = 403,
                            CourseId = 305
                        },
                        new
                        {
                            StudentId = 404,
                            CourseId = 307
                        },
                        new
                        {
                            StudentId = 405,
                            CourseId = 309
                        },
                        new
                        {
                            StudentId = 406,
                            CourseId = 311
                        },
                        new
                        {
                            StudentId = 407,
                            CourseId = 313
                        },
                        new
                        {
                            StudentId = 408,
                            CourseId = 315
                        },
                        new
                        {
                            StudentId = 409,
                            CourseId = 317
                        },
                        new
                        {
                            StudentId = 410,
                            CourseId = 319
                        },
                        new
                        {
                            StudentId = 411,
                            CourseId = 301
                        },
                        new
                        {
                            StudentId = 412,
                            CourseId = 303
                        },
                        new
                        {
                            StudentId = 413,
                            CourseId = 305
                        },
                        new
                        {
                            StudentId = 414,
                            CourseId = 307
                        },
                        new
                        {
                            StudentId = 415,
                            CourseId = 309
                        },
                        new
                        {
                            StudentId = 416,
                            CourseId = 311
                        },
                        new
                        {
                            StudentId = 417,
                            CourseId = 313
                        },
                        new
                        {
                            StudentId = 418,
                            CourseId = 315
                        },
                        new
                        {
                            StudentId = 419,
                            CourseId = 317
                        },
                        new
                        {
                            StudentId = 420,
                            CourseId = 319
                        });
                });

            modelBuilder.Entity("University_Managment_system.Entity.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Full Name");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Password");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 401,
                            DeptId = 1,
                            Email = "mohamed.ahmed@university.edu.eg",
                            FullName = "Mohamed Ahmed",
                            GPA = 3.5,
                            Password = "student123",
                            level = 1
                        },
                        new
                        {
                            Id = 402,
                            DeptId = 2,
                            Email = "ali.hassan@university.edu.eg",
                            FullName = "Ali Hassan",
                            GPA = 3.7999999999999998,
                            Password = "student456",
                            level = 2
                        },
                        new
                        {
                            Id = 403,
                            DeptId = 3,
                            Email = "fatma.mahmoud@university.edu.eg",
                            FullName = "Fatma Mahmoud",
                            GPA = 3.6000000000000001,
                            Password = "student789",
                            level = 1
                        },
                        new
                        {
                            Id = 404,
                            DeptId = 4,
                            Email = "youssef.ali@university.edu.eg",
                            FullName = "Youssef Ali",
                            GPA = 3.8999999999999999,
                            Password = "student101",
                            level = 2
                        },
                        new
                        {
                            Id = 405,
                            DeptId = 1,
                            Email = "nada.samir@university.edu.eg",
                            FullName = "Nada Samir",
                            GPA = 3.7000000000000002,
                            Password = "student202",
                            level = 3
                        },
                        new
                        {
                            Id = 406,
                            DeptId = 2,
                            Email = "karim.adel@university.edu.eg",
                            FullName = "Karim Adel",
                            GPA = 3.3999999999999999,
                            Password = "student303",
                            level = 4
                        },
                        new
                        {
                            Id = 407,
                            DeptId = 3,
                            Email = "hana.tarek@university.edu.eg",
                            FullName = "Hana Tarek",
                            GPA = 3.7999999999999998,
                            Password = "student404",
                            level = 3
                        },
                        new
                        {
                            Id = 408,
                            DeptId = 4,
                            Email = "omar.ibrahim@university.edu.eg",
                            FullName = "Omar Ibrahim",
                            GPA = 3.6000000000000001,
                            Password = "student505",
                            level = 4
                        },
                        new
                        {
                            Id = 409,
                            DeptId = 1,
                            Email = "rana.sherif@university.edu.eg",
                            FullName = "Rana Sherif",
                            GPA = 3.8999999999999999,
                            Password = "student606",
                            level = 1
                        },
                        new
                        {
                            Id = 410,
                            DeptId = 2,
                            Email = "tamer.nabil@university.edu.eg",
                            FullName = "Tamer Nabil",
                            GPA = 3.5,
                            Password = "student707",
                            level = 2
                        },
                        new
                        {
                            Id = 411,
                            DeptId = 3,
                            Email = "dina.hossam@university.edu.eg",
                            FullName = "Dina Hossam",
                            GPA = 3.7000000000000002,
                            Password = "student808",
                            level = 1
                        },
                        new
                        {
                            Id = 412,
                            DeptId = 4,
                            Email = "sherif.omar@university.edu.eg",
                            FullName = "Sherif Omar",
                            GPA = 3.7999999999999998,
                            Password = "student909",
                            level = 2
                        },
                        new
                        {
                            Id = 413,
                            DeptId = 1,
                            Email = "laila.ahmed@university.edu.eg",
                            FullName = "Laila Ahmed",
                            GPA = 3.6000000000000001,
                            Password = "student1010",
                            level = 3
                        },
                        new
                        {
                            Id = 414,
                            DeptId = 2,
                            Email = "hassan.mohamed@university.edu.eg",
                            FullName = "Hassan Mohamed",
                            GPA = 3.8999999999999999,
                            Password = "student1111",
                            level = 4
                        },
                        new
                        {
                            Id = 415,
                            DeptId = 3,
                            Email = "nour.ali@university.edu.eg",
                            FullName = "Nour Ali",
                            GPA = 3.5,
                            Password = "student1212",
                            level = 3
                        },
                        new
                        {
                            Id = 416,
                            DeptId = 4,
                            Email = "amr.tarek@university.edu.eg",
                            FullName = "Amr Tarek",
                            GPA = 3.7000000000000002,
                            Password = "student1313",
                            level = 4
                        },
                        new
                        {
                            Id = 417,
                            DeptId = 1,
                            Email = "sara.khaled@university.edu.eg",
                            FullName = "Sara Khaled",
                            GPA = 3.7999999999999998,
                            Password = "student1414",
                            level = 1
                        },
                        new
                        {
                            Id = 418,
                            DeptId = 2,
                            Email = "kareem.samir@university.edu.eg",
                            FullName = "Kareem Samir",
                            GPA = 3.6000000000000001,
                            Password = "student1515",
                            level = 2
                        },
                        new
                        {
                            Id = 419,
                            DeptId = 3,
                            Email = "dalia.adel@university.edu.eg",
                            FullName = "Dalia Adel",
                            GPA = 3.8999999999999999,
                            Password = "student1616",
                            level = 1
                        },
                        new
                        {
                            Id = 420,
                            DeptId = 4,
                            Email = "ahmed.youssef@university.edu.eg",
                            FullName = "Ahmed Youssef",
                            GPA = 3.7000000000000002,
                            Password = "student1717",
                            level = 2
                        });
                });

            modelBuilder.Entity("University_Managment_system.Entity.TeacherAssistant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Full Name");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DeptId");

                    b.ToTable("TeacherAssistants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 501,
                            CourseId = 301,
                            DeptId = 1,
                            Email = "ahmed.samir@university.edu.eg",
                            FullName = "Ahmed Samir"
                        },
                        new
                        {
                            Id = 502,
                            CourseId = 303,
                            DeptId = 2,
                            Email = "mona.adel@university.edu.eg",
                            FullName = "Mona Adel"
                        },
                        new
                        {
                            Id = 503,
                            CourseId = 305,
                            DeptId = 3,
                            Email = "youssef.tarek@university.edu.eg",
                            FullName = "Youssef Tarek"
                        },
                        new
                        {
                            Id = 504,
                            CourseId = 307,
                            DeptId = 4,
                            Email = "fatma.sherif@university.edu.eg",
                            FullName = "Fatma Sherif"
                        },
                        new
                        {
                            Id = 505,
                            CourseId = 309,
                            DeptId = 1,
                            Email = "omar.hossam@university.edu.eg",
                            FullName = "Omar Hossam"
                        },
                        new
                        {
                            Id = 506,
                            CourseId = 311,
                            DeptId = 2,
                            Email = "nada.khaled@university.edu.eg",
                            FullName = "Nada Khaled"
                        },
                        new
                        {
                            Id = 507,
                            CourseId = 313,
                            DeptId = 3,
                            Email = "karim.nabil@university.edu.eg",
                            FullName = "Karim Nabil"
                        },
                        new
                        {
                            Id = 508,
                            CourseId = 315,
                            DeptId = 4,
                            Email = "hana.ali@university.edu.eg",
                            FullName = "Hana Ali"
                        },
                        new
                        {
                            Id = 509,
                            CourseId = 317,
                            DeptId = 1,
                            Email = "ali.mahmoud@university.edu.eg",
                            FullName = "Ali Mahmoud"
                        },
                        new
                        {
                            Id = 510,
                            CourseId = 319,
                            DeptId = 2,
                            Email = "rana.ibrahim@university.edu.eg",
                            FullName = "Rana Ibrahim"
                        },
                        new
                        {
                            Id = 511,
                            CourseId = 301,
                            DeptId = 3,
                            Email = "tamer.mohamed@university.edu.eg",
                            FullName = "Tamer Mohamed"
                        },
                        new
                        {
                            Id = 512,
                            CourseId = 303,
                            DeptId = 4,
                            Email = "dina.hassan@university.edu.eg",
                            FullName = "Dina Hassan"
                        },
                        new
                        {
                            Id = 513,
                            CourseId = 305,
                            DeptId = 1,
                            Email = "sherif.samir@university.edu.eg",
                            FullName = "Sherif Samir"
                        },
                        new
                        {
                            Id = 514,
                            CourseId = 307,
                            DeptId = 2,
                            Email = "laila.adel@university.edu.eg",
                            FullName = "Laila Adel"
                        },
                        new
                        {
                            Id = 515,
                            CourseId = 309,
                            DeptId = 3,
                            Email = "hassan.tarek@university.edu.eg",
                            FullName = "Hassan Tarek"
                        },
                        new
                        {
                            Id = 516,
                            CourseId = 311,
                            DeptId = 4,
                            Email = "nour.sherif@university.edu.eg",
                            FullName = "Nour Sherif"
                        },
                        new
                        {
                            Id = 517,
                            CourseId = 313,
                            DeptId = 1,
                            Email = "amr.hossam@university.edu.eg",
                            FullName = "Amr Hossam"
                        },
                        new
                        {
                            Id = 518,
                            CourseId = 315,
                            DeptId = 2,
                            Email = "sara.khaled@university.edu.eg",
                            FullName = "Sara Khaled"
                        },
                        new
                        {
                            Id = 519,
                            CourseId = 317,
                            DeptId = 3,
                            Email = "kareem.nabil@university.edu.eg",
                            FullName = "Kareem Nabil"
                        },
                        new
                        {
                            Id = 520,
                            CourseId = 319,
                            DeptId = 4,
                            Email = "dalia.ali@university.edu.eg",
                            FullName = "Dalia Ali"
                        });
                });

            modelBuilder.Entity("University_Managment_system.Entity.Admin", b =>
                {
                    b.HasOne("University_Managment_system.Entity.Department", "Department")
                        .WithOne("Admin")
                        .HasForeignKey("University_Managment_system.Entity.Admin", "DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("University_Managment_system.Entity.Course", b =>
                {
                    b.HasOne("University_Managment_system.Entity.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("University_Managment_system.Entity.Doctor", "Doctor")
                        .WithMany("Courses")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("University_Managment_system.Entity.Doctor", b =>
                {
                    b.HasOne("University_Managment_system.Entity.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("University_Managment_system.Entity.Enrollment", b =>
                {
                    b.HasOne("University_Managment_system.Entity.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Managment_system.Entity.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University_Managment_system.Entity.Student", b =>
                {
                    b.HasOne("University_Managment_system.Entity.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("University_Managment_system.Entity.TeacherAssistant", b =>
                {
                    b.HasOne("University_Managment_system.Entity.Course", "Course")
                        .WithMany("TeacherAssistants")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Managment_system.Entity.Department", "Department")
                        .WithMany("TeacherAssistants")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("University_Managment_system.Entity.Course", b =>
                {
                    b.Navigation("TeacherAssistants");
                });

            modelBuilder.Entity("University_Managment_system.Entity.Department", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Doctors");

                    b.Navigation("Students");

                    b.Navigation("TeacherAssistants");
                });

            modelBuilder.Entity("University_Managment_system.Entity.Doctor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
